apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-app
  template:
    metadata:
      labels:
        app: ticket-app
    spec:
      containers:
        - name: ticket-app
          image: rahulsingh1207/ticket-booking:latest  # ✅ your DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ticket-app-config
