apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: ticket-system
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306        # The port your app will connect to inside the cluster
      targetPort: 3306  # Port on the pod
  type: ClusterIP       # Internal service only (used by ticket-app)
