apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: ticket-system
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11          # Use public image
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Rahul@1234"
            - name: MYSQL_DATABASE
              value: "ticketdb"
            - name: MYSQL_USER
              value: "ticketuser"
            - name: MYSQL_PASSWORD
              value: "secret"
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
