apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  username: bWFyaWFkYg==        # base64 for "mariadb"
  password: cGFzc3dvcmQ=        # base64 for "password"
  rootpassword: cm9vdHBhc3M=    # base64 for "rootpass"
