apiVersion: v1
kind: Service
metadata:
  name: ticket-app-service
  namespace: ticket-system
spec:
  selector:
    app: ticket-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
